# Build toolchain for programs running on embedded system (Ascend device)
SET(CMAKE_SYSTEM_NAME           Linux)
SET(CMAKE_SYSTEM_PROCESSOR      aarch64)
SET(HCC                         ${ASCEND_TOOLKIT_PATH}/toolkit/toolchain/hcc)
SET(CMAKE_SYSROOT               ${HCC}/sysroot)
SET(CMAKE_C_COMPILER            ${HCC}/bin/aarch64-target-linux-gnu-gcc)
SET(CMAKE_CXX_COMPILER          ${HCC}/bin/aarch64-target-linux-gnu-g++)
SET(CMAKE_AR                    ${HCC}/bin/aarch64-target-linux-gnu-ar)
SET(CMAKE_RANLIB                ${HCC}/bin/aarch64-target-linux-gnu-ranlib)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)