# Generate CRoaring amalgamation (roaring.c / roaring.h) into the build tree.
IF(DEFINED CROARING_AMALGAM_C)
    RETURN()
ENDIF()

GET_FILENAME_COMPONENT(CROARING_ROOT "${CMAKE_CURRENT_LIST_DIR}/../third_party/CRoaring" ABSOLUTE)
SET(CROARING_AMALGAM_SH "${CROARING_ROOT}/amalgamation.sh")
IF(NOT EXISTS "${CROARING_AMALGAM_SH}")
    EXECUTE_PROCESS(COMMAND git rev-parse --show-toplevel
        WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}"
        RESULT_VARIABLE _CROARING_GIT_ROOT_RV OUTPUT_VARIABLE _CROARING_GIT_ROOT
        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    IF(_CROARING_GIT_ROOT_RV EQUAL 0)
        EXECUTE_PROCESS(COMMAND git submodule update --init --recursive
            WORKING_DIRECTORY "${_CROARING_GIT_ROOT}")
    ENDIF()
ENDIF()
IF(NOT EXISTS "${CROARING_AMALGAM_SH}")
    MESSAGE(FATAL_ERROR "CRoaring submodule missing (${CROARING_AMALGAM_SH}). Run: git submodule update --init --recursive")
ENDIF()

SET(CROARING_AMALGAM_DIR "${CMAKE_BINARY_DIR}/generated/croaring")
SET(CROARING_AMALGAM_C "${CROARING_AMALGAM_DIR}/roaring.c")
SET(CROARING_AMALGAM_H "${CROARING_AMALGAM_DIR}/roaring.h")
SET(CROARING_AMALGAM_INCLUDE_DIR "${CROARING_AMALGAM_DIR}")
SET(CROARING_STAMP "${CROARING_AMALGAM_DIR}/.croaring_git_rev")
EXECUTE_PROCESS(COMMAND git rev-parse HEAD WORKING_DIRECTORY "${CROARING_ROOT}"
    RESULT_VARIABLE _CROARING_REV_RV OUTPUT_VARIABLE CROARING_GIT_REV
    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
IF(NOT _CROARING_REV_RV EQUAL 0 OR "${CROARING_GIT_REV}" STREQUAL "")
    SET(CROARING_GIT_REV "unknown")
ENDIF()

SET(_CROARING_NEED_AMALGAM FALSE)
IF(NOT EXISTS "${CROARING_AMALGAM_C}" OR NOT EXISTS "${CROARING_AMALGAM_H}" OR NOT EXISTS "${CROARING_STAMP}")
    SET(_CROARING_NEED_AMALGAM TRUE)
ELSE()
    FILE(READ "${CROARING_STAMP}" _CROARING_OLD_REV)
    STRING(STRIP "${_CROARING_OLD_REV}" _CROARING_OLD_REV)
    IF(NOT _CROARING_OLD_REV STREQUAL "${CROARING_GIT_REV}")
        SET(_CROARING_NEED_AMALGAM TRUE)
    ENDIF()
ENDIF()
IF(_CROARING_NEED_AMALGAM)
    FILE(MAKE_DIRECTORY "${CROARING_AMALGAM_DIR}")
    EXECUTE_PROCESS(COMMAND bash "${CROARING_AMALGAM_SH}" "${CROARING_AMALGAM_DIR}"
        RESULT_VARIABLE _CROARING_AMALGAM_RV)
    IF(NOT _CROARING_AMALGAM_RV EQUAL 0)
        MESSAGE(FATAL_ERROR "CRoaring amalgamation.sh failed (${_CROARING_AMALGAM_RV})")
    ENDIF()
    FILE(WRITE "${CROARING_STAMP}" "${CROARING_GIT_REV}\n")
ENDIF()
IF(NOT EXISTS "${CROARING_AMALGAM_C}" OR NOT EXISTS "${CROARING_AMALGAM_H}")
    MESSAGE(FATAL_ERROR "CRoaring amalgamation did not produce roaring.c/h in ${CROARING_AMALGAM_DIR}")
ENDIF()
SET_SOURCE_FILES_PROPERTIES("${CROARING_AMALGAM_C}" PROPERTIES COMPILE_FLAGS "-w")
MESSAGE(STATUS "CRoaring amalgamation: ${CROARING_AMALGAM_C} (rev ${CROARING_GIT_REV})")
