on:
  workflow_call:
    inputs:
      REMOTE_URL:
        required: false
        type: string
        default: ${{ atomgit.repositoryurl }}
      pr_id:
        required: false
        type: string
        default: ${{ atomgit.event.pull_request.number }}
      IMAGE_FLAG:
        required: true
        type: string
        description: "Full SWR image URL, e.g. swr.<region>.<org>/mindx_arm:tag"
      TARGET_BRANCH:
        required: false
        type: string
        default: ${{ atomgit.event.pull_request.base.ref }}
      runs_on_arch:
        required: true
        type: string
        description: "x86 or arm"
      servicename:
        required: false
        type: string
        default: $(echo "${{ atomgit.repository }}" | cut -d '/' -f 2)
      DEFAULT_BRANCH:
        required: false
        type: string
        default: "master"

jobs:
  JOB_compile:
    name: JOB_compile
    select: selected_by_default
    runs-on: [ self-hosted, "${{ inputs.runs_on_arch }}", cpu=32 ]
    container:
      image: ${{ inputs.IMAGE_FLAG }}
      options: --user root
    steps:
      - name: clone repo and merge PR
        run: |
          set -x
          artifact_directory="${ATOMGIT_WORKSPACE}/artifacts"
          mkdir -p "${artifact_directory}"
          touch "${artifact_directory}/empty.run"

          git clone --no-tags --single-branch -b ${{ inputs.TARGET_BRANCH }} ${{ inputs.REMOTE_URL }} ${{ inputs.servicename }}
          cd ${{ inputs.servicename }}

          git fetch --no-tags origin refs/merge-requests/${{ inputs.pr_id }}/head:pr_${{ inputs.pr_id }}
          git reset --hard "origin/${{ inputs.TARGET_BRANCH }}"
          git checkout -b new_${{ inputs.TARGET_BRANCH }}
          git config --global user.name AtlasAccount
          git config --global user.email AtlasAccount@noreply.gitcode.com
          git merge --no-edit pr_${{ inputs.pr_id }}
          git diff-tree -r --name-only --no-commit-id origin/${{ inputs.TARGET_BRANCH }} HEAD > ${ATOMGIT_WORKSPACE}/change.txt
          cat ${ATOMGIT_WORKSPACE}/change.txt

          if [ "${{ inputs.TARGET_BRANCH }}" != "${{ inputs.DEFAULT_BRANCH }}" ]; then
              mkdir -p .gitcode/workflows
              git clone --no-tags --single-branch --depth 1 -b ${{ inputs.DEFAULT_BRANCH }} ${{ inputs.REMOTE_URL }} ${ATOMGIT_WORKSPACE}/tempdir
              cp -fr ${ATOMGIT_WORKSPACE}/tempdir/.gitcode/workflows/scripts .gitcode/workflows/ 2>/dev/null || true
              cp -fr ${ATOMGIT_WORKSPACE}/tempdir/.gitcode/workflows/config .gitcode/workflows/ 2>/dev/null || true
              rm -fr ${ATOMGIT_WORKSPACE}/tempdir
          fi

      - name: prepare_dependency
        run: |
          set -e
          echo "ATOMGIT_WORKSPACE=${ATOMGIT_WORKSPACE}"

          cd ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/
          git clone -b v2.5.0.x https://gitcode.com/cann-src-third-party/makeself.git makeself_patch
          git clone -b release-2.5.0 https://gitcode.com/gh_mirrors/ma/makeself.git
          git clone -b v2.7.x-h3 https://gitcode.com/cann-src-third-party/mockcpp.git mockcpp_patch
          git clone -b v2.7 https://gitcode.com/Ascend/mockcpp.git mockcpp
          git clone -b release-1.11.0 https://gitcode.com/GitHub_Trending/go/googletest.git googletest

          # platform dependency
          if [ ! -d "${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/feature_retrieval/secondparty" ]; then
              mkdir -p ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/feature_retrieval/secondparty
          fi
          cd ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/feature_retrieval/secondparty/
          git clone -b v1.1.16 https://gitee.com/openeuler/libboundscheck.git huawei_secure_c
          cp -rf huawei_secure_c ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/

      - name: compile
        run: |
          set -ex
          cd ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/
          export MULTI_FAISS_PACKAGE=OFF
          export DEFAULT_FAISS_ABI=faiss1.14
          export FAISS_114_HOME=/usr/local/faiss/faiss1.14.1
          bash build/build.sh ut
          cat feature_retrieval/ut/output/coverage/report/total/index.html
          cat feature_retrieval/ut/output/coverage/report/test_detail.xml
