string(ASCII 27 Esc)
set(RED "${Esc}[0;31m")
set(GREEN "${Esc}[1;32m")
set(YELLOW "${Esc}[1;33m")
set(BLUE "${Esc}[1;34m")
set(END "${Esc}[m")

IF(NOT DEFINED FAISS_HOME)
    IF(DEFINED ENV{FAISS_HOME} AND NOT "$ENV{FAISS_HOME}" STREQUAL "")
        SET(FAISS_HOME "$ENV{FAISS_HOME}" CACHE PATH "Faiss installation directory")
    ELSE()
        SET(FAISS_HOME /usr/local/faiss CACHE PATH "Faiss installation directory")
    ENDIF()
ENDIF()

SET(PROTOBUF_HOME /usr/local/protobuf)
SET(ASCEND_PROJECT_HOME ${PROJECT_SOURCE_DIR}/..)
SET(OPEN_SOURCE_HOME ${ASCEND_PROJECT_HOME}/../../opensource)
SET(GTEST_HOME ${OPEN_SOURCE_HOME}/../../gtest_install)
