/*
 * -------------------------------------------------------------------------
 * This file is part of the IndexSDK project.
 * Copyright (c) 2025 Huawei Technologies Co.,Ltd.
 *
 * IndexSDK is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *
 *          http://license.coscl.org.cn/MulanPSL2
 *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 * -------------------------------------------------------------------------
 */


#ifndef AICPU_KERNEL_SHARED_DEF_H
#define AICPU_KERNEL_SHARED_DEF_H

#include <cstdlib>

namespace aicpu {
enum TopkFlatAttrIdx : int32_t {
    TOPK_FLAT_ATTR_ASC_IDX = 0,
    TOPK_FLAT_ATTR_K_IDX,
    TOPK_FLAT_ATTR_BURST_LEN_IDX,
    TOPK_FLAT_ATTR_BLOCK_NUM_IDX,
    TOPK_FLAT_ATTR_PAGE_IDX,
    TOPK_FLAT_ATTR_PAGE_NUM_IDX,
    TOPK_FLAT_ATTR_PAGE_SIZE_IDX,
    TOPK_FLAT_ATTR_QUICK_HEAP,
    TOPK_FLAT_ATTR_BLOCK_SIZE,
    TOPK_FLAT_ATTR_IDX_COUNT,
};

enum TopkIvfSpL1AttrIdx : int32_t {
    TOPK_IVFSP_L1_ATTR_ASC_IDX = 0,
    TOPK_IVFSP_L1_ATTR_K_IDX,
    TOPK_IVFSP_L1_ATTR_QUICK_HEAP,
    TOPK_IVFSP_L1_ATTR_IDX_COUNT,
};

enum TopkSpSqAttrIdx : int32_t {
    TOPK_SPSQ_ATTR_ASC_IDX = 0,
    TOPK_SPSQ_ATTR_K_IDX,
    TOPK_SPSQ_ATTR_BURST_LEN_IDX,
    TOPK_SPSQ_ATTR_BLOCK_NUM_IDX,
    TOPK_SPSQ_ATTR_PAGE_IDX,
    TOPK_SPSQ_ATTR_PAGE_NUM_IDX,
    TOPK_SPSQ_ATTR_PAGE_SIZE_IDX,
    TOPK_SPSQ_ATTR_QUICK_HEAP,
    TOPK_SPSQ_ATTR_BLOCK_SIZE,
    TOPK_SPSQ_ATTR_BI_NUM_SIZE,
    TOPK_SPSQ_ATTR_BLOCK_NUM_SIZE,
    TOPK_SPSQ_ATTR_IDX_COUNT,
};


enum TopkIvfSpAttrIdx : int32_t {
    TOPK_IVF_SP_ATTR_ASC_IDX = 0,
    TOPK_IVF_SP_ATTR_K_IDX,
    TOPK_IVF_SP_ATTR_BURST_LEN_IDX,
    TOPK_IVF_SP_ATTR_BLOCK_NUM_IDX,
    TOPK_IVF_SP_ATTR_FLAG_NUM_IDX,
    TOPK_IVF_SP_ATTR_IDX_COUNT,
};

enum TopkMultisearchIvfAttrIdx : int32_t {
    TOPK_MULTISEARCH_IVF_ATTR_ASC_IDX = 0,
    TOPK_MULTISEARCH_IVF_ATTR_K_IDX,
    TOPK_MULTISEARCH_IVF_ATTR_BURST_LEN_IDX,
    TOPK_MULTISEARCH_IVF_ATTR_BLOCK_NUM_IDX,
    TOPK_MULTISEARCH_IVF_ATTR_FLAG_NUM_IDX,
    TOPK_MULTISEARCH_IVF_ATTR_MAX_INDEX_NUM_IDX,
    TOPK_MULTISEARCH_IVF_ATTR_INDEX_NUM_IDX,
    TOPK_MULTISEARCH_IVF_ATTR_IDX_COUNT,
};

enum TopkMultisearchIvV2AttrIdx : int32_t {
    TOPK_MULTISEARCH_IVF_V2_ATTR_ASC_IDX = 0,
    TOPK_MULTISEARCH_IVF_V2_ATTR_K_IDX,
    TOPK_MULTISEARCH_IVF_V2_ATTR_BURST_LEN_IDX,
    TOPK_MULTISEARCH_IVF_V2_ATTR_BLOCK_NUM_IDX,
    TOPK_MULTISEARCH_IVF_V2_ATTR_FLAG_NUM_IDX,
    TOPK_MULTISEARCH_IVF_V2_ATTR_MAX_INDEX_NUM_IDX,
    TOPK_MULTISEARCH_IVF_V2_ATTR_INDEX_NUM_IDX,
    TOPK_MULTISEARCH_IVF_V2_ATTR_Q_IDX,
    TOPK_MULTISEARCH_IVF_V2_ATTR_IDX_COUNT,
};


enum TransdataShapedSpAttrIdx : int32_t {
    TRANSDATA_SHAPED_SP_ATTR_NTOTAL_IDX = 0,
    TRANSDATA_SHAPED_SP_ATTR_IDX_COUNT,
};

enum TransdataRawSpAttrIdx : int32_t {
    TRANSDATA_RAW_SP_ATTR_OFFSET_IDX = 0,
    TRANSDATA_RAW_SP_ATTR_IDX_COUNT,
};

enum TakeCareOfVoidClusterAttrIdx : int32_t {
    TAKE_CARE_OF_VOID_CLUSTER_K_IDX = 0,
    TAKE_CARE_OF_VOID_CLUSTER_N_IDX = 1,
    TAKE_CARE_OF_VOID_CLUSTER_IDX_COUNT,
};
} // namespace aicpu

#endif